# Generated by Django 4.2.7 on 2023-12-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=123, upload_to='pics'),
            preserve_default=False,
        ),
    ]
